name: "Build"
on:
  push:
    branches:
      - "master"
permissions:
  contents: read
  packages: write
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Set up JDK"
        uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Build"
        uses: "burrunan/gradle-cache-action@v1"
        with:
          arguments: "--info publish -Pversion=${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
